version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Configuration générée
      - ./nginx/certs:/etc/nginx/certs:ro           # Certificats SSL
      - ./frontend:/usr/share/nginx/html:ro         # Fichiers frontend
    restart: always
