"""
Django settings for player project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from os import getenv

# === 1. Chemins dynamiques ===
BASE_DIR = Path(__file__).resolve().parent  # backend/player/api/
PLAYER_DIR = BASE_DIR.parent  # backend/player/
BACKEND_DIR = PLAYER_DIR.parent  # backend/
PROJECT_ROOT = BACKEND_DIR.parent  # Racine du projet

# === 2. Sécurité ===
SECRET_KEY = getenv("DJANGO_SECRET_KEY")  # Clé par défaut si non définie
DEBUG = True  # Toujours en mode debug pour le développement local
ALLOWED_HOSTS = ["localhost"]  # Autoriser uniquement localhost

# === 3. Applications Django ===
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",  # Django REST Framework
    "api",  # Application spécifique au microservice player
]

# === 4. Middlewares ===
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# === 5. URLs et point d'entrée ===
ROOT_URLCONF = "api.urls"  # Chemin vers le fichier urls.py de l'application
WSGI_APPLICATION = "api.wsgi.application"

# === 6. Base de données ===
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": getenv("POSTGRES_DB"),  # Nom de la base par défaut si non défini
        "USER": getenv("POSTGRES_USER"),  # Utilisateur par défaut
        "PASSWORD": getenv("POSTGRES_PASSWORD"),  # Mot de passe par défaut
        "HOST": getenv("POSTGRES_HOST"),  # Hôte PostgreSQL (localhost)
        "PORT": getenv("POSTGRES_PORT")  # Port PostgreSQL
    }
}

# === 7. Validation des mots de passe ===
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# === 8. Internationalisation ===
LANGUAGE_CODE = "en-us"  # Langue par défaut
TIME_ZONE = "Europe/Paris"  # Zone horaire française
USE_I18N = True
USE_TZ = True

# === 9. Fichiers statiques et médias ===
STATIC_URL = "/static/"
STATIC_ROOT = PLAYER_DIR / "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = PLAYER_DIR / "media/"

# === 10. Authentification ===
AUTH_USER_MODEL = "api.Player"  # Modèle utilisateur personnalisé (Player)
